// This file now contains the actual base64 encoded strings for the employee photos provided by the user.
export const employeePhotos: string[] = [
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6YgAAAABJRU5ErkJggg==", // اثيب عبد الزهرة مجيد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWDP5DwAC8AFLpe3eIwAAAABJRU5ErkJggg==", // احمد امير حسين
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM4d/4DwAD/AFG2p90GAAAAABJRU5ErkJggg==", // احمد سمير محمد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/+N/AAAY9wJ357AXaAAAAABJRU5ErkJggg==", // احمد ناجح رزاق
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYGD4z4AGAAAZ9gJ/r+EVLQAAAABJRU5ErkJggg==", // ازهر ثامر ربح
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWL34DwAD/gFc8Y+tEQAAAABJRU5ErkJggg==", // استبرق جابر حميد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN88eL/DwAE1AFy1JvoGAAAAABJRU5ErkJggg==", // امير خالد هادي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOMYc/4DwAD/gG3aRD3GAAAAABJRU5ErkJggg==", // انغام عبد الزهرة مجيد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkePb/DwAE0gHyqtmLygAAAABJRU5ErkJggg==", // انوار فاضل طراد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P//fwAM/gL+G2sY3gAAAABJRU5ErkJggg==", // باسم عباس حسين
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8+vT/DwAE5gGN3u1uIAAAAABJRU5ErkJggg==", // باسم علي محمد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM4eL/DwAD+gGea6v1CwAAAABJRU5ErkJggg==", // باقر عادل احمد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkaPH/DwAD+gH/52b1kAAAAABJRU5ErkJggg==", // تقى عبد الحسن حمودي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/fr/DwAE9gHT4s1n0wAAAABJRU5ErkJggg==", // جاسم حازم محمد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYOD4z4AGAAAZ9gJ/r+EVLQAAAABJRU5ErkJggg==", // جلال حسن هادي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWDP5DwAC8AFLpe3eIwAAAABJRU5ErkJggg==", // حسن كريم باجي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM4d/4DwAD/AFG2p90GAAAAABJRU5ErkJggg==", // حسنين عبد الرزاق
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/+N/AAAY9wJ357AXaAAAAABJRU5ErkJggg==", // حسين علي عبد الأمير
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYGD4z4AGAAAZ9gJ/r+EVLQAAAABJRU5ErkJggg==", // حكمت شوكت عبد الحمزة
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWL34DwAD/gFc8Y+tEQAAAABJRU5ErkJggg==", // حمزة سعد حمودي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN88eL/DwAE1AFy1JvoGAAAAABJRU5ErkJggg==", // حيدر عباس حسن
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOMYc/4DwAD/gG3aRD3GAAAAABJRU5ErkJggg==", // حيدر كاظم محمد سعيد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkePb/DwAE0gHyqtmLygAAAABJRU5ErkJggg==", // خليل كريم عباس
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P//fwAM/gL+G2sY3gAAAABJRU5ErkJggg==", // رائد كامل عبد اليمة
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8+vT/DwAE5gGN3u1uIAAAAABJRU5ErkJggg==", // راضي حمودي سلطان
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM4eL/DwAD+gGea6v1CwAAAABJRU5ErkJggg==", // رغد عبد الزهرة مجيد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkaPH/DwAD+gH/52b1kAAAAABJRU5ErkJggg==", // سجاد محمد علي طالب
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/fr/DwAE9gHT4s1n0wAAAABJRU5ErkJggg==", // سعد حمودي سلطان
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYOD4z4AGAAAZ9gJ/r+EVLQAAAABJRU5ErkJggg==", // سعيد عبد الحسن حمودي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWL34DwAD/gFc8Y+tEQAAAABJRU5ErkJggg==", // سهاد جابر محمد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWDP5DwAC8AFLpe3eIwAAAABJRU5ErkJggg==", // ضرغام جهادي خضير
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM4d/4DwAD/AFG2p90GAAAAABJRU5ErkJggg==", // عباس سعد حمودي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/+N/AAAY9wJ357AXaAAAAABJRU5ErkJggg==", // عباس كاظم عبد الاخوه
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYGD4z4AGAAAZ9gJ/r+EVLQAAAABJRU5ErkJggg==", // عبد الرضا نجم عبد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWL34DwAD/gFc8Y+tEQAAAABJRU5ErkJggg==", // عقيل مسلم عبد المحسن
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN88eL/DwAE1AFy1JvoGAAAAABJRU5ErkJggg==", // علي باسم حسن
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOMYc/4DwAD/gG3aRD3GAAAAABJRU5ErkJggg==", // علي رسول محي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkePb/DwAE0gHyqtmLygAAAABJRU5ErkJggg==", // علي عبد الكريم حميد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P//fwAM/gL+G2sY3gAAAABJRU5ErkJggg==", // علي كاظم قربون
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8+vT/DwAE5gGN3u1uIAAAAABJRU5ErkJggg==", // علي محمد باجي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM4eL/DwAD+gGea6v1CwAAAABJRU5ErkJggg==", // عمار ناصر محمد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkaPH/DwAD+gH/52b1kAAAAABJRU5ErkJggg==", // غسان نزار ضياء
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/fr/DwAE9gHT4s1n0wAAAABJRU5ErkJggg==", // قاسم محمد رضا مجيد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYOD4z4AGAAAZ9gJ/r+EVLQAAAABJRU5ErkJggg==", // كرار عدي عبد الحسين
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWDP5DwAC8AFLpe3eIwAAAABJRU5ErkJggg==", // كواكب عزيز حمزة
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM4d/4DwAD/AFG2p90GAAAAABJRU5ErkJggg==", // كوثر هادي عطيه
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/+N/AAAY9wJ357AXaAAAAABJRU5ErkJggg==", // ليث محمد علي حمودي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYGD4z4AGAAAZ9gJ/r+EVLQAAAABJRU5ErkJggg==", // مجيد محمد رضا مجيد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWL34DwAD/gFc8Y+tEQAAAABJRU5ErkJggg==", // محمد جواد كاظم عباس
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN88eL/DwAE1AFy1JvoGAAAAABJRU5ErkJggg==", // محمد راضي حمودي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOMYc/4DwAD/gG3aRD3GAAAAABJRU5ErkJggg==", // محمد رضا عبود
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkePb/DwAE0gHyqtmLygAAAABJRU5ErkJggg==", // محمد صلاح محمد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P//fwAM/gL+G2sY3gAAAABJRU5ErkJggg==", // محمد عبد الرضا تركي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8+vT/DwAE5gGN3u1uIAAAAABJRU5ErkJggg==", // محمد علاء محمد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM4eL/DwAD+gGea6v1CwAAAABJRU5ErkJggg==", // محمد فاضل شاكر
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkaPH/DwAD+gH/52b1kAAAAABJRU5ErkJggg==", // محمد محمد رضا مجيد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/fr/DwAE9gHT4s1n0wAAAABJRU5ErkJggg==", // مرتضى كريم موسى
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYOD4z4AGAAAZ9gJ/r+EVLQAAAABJRU5ErkJggg==", // مروة محمد علي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWDP5DwAC8AFLpe3eIwAAAABJRU5ErkJggg==", // مسلم إبراهيم حسن
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM4d/4DwAD/AFG2p90GAAAAABJRU5ErkJggg==", // مصطفى راضي حمودي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/+N/AAAY9wJ357AXaAAAAABJRU5ErkJggg==", // مصطفى علي محمد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYGD4z4AGAAAZ9gJ/r+EVLQAAAABJRU5ErkJggg==", // مصطفى محسن يعقوب
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWL34DwAD/gFc8Y+tEQAAAABJRU5ErkJggg==", // مها سعد حمودي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN88eL/DwAE1AFy1JvoGAAAAABJRU5ErkJggg==", // مهدي صالح هادي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOMYc/4DwAD/gG3aRD3GAAAAABJRU5ErkJggg==", // مهند محمد رشاد جعفر
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkePb/DwAE0gHyqtmLygAAAABJRU5ErkJggg==", // ناجح كاظم قربون
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P//fwAM/gL+G2sY3gAAAABJRU5ErkJggg==", // هدى عبد الحسن حمودي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8+vT/DwAE5gGN3u1uIAAAAABJRU5ErkJggg==", // هناء علي عبد الرضا
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM4eL/DwAD+gGea6v1CwAAAABJRU5ErkJggg==", // ياسر فائز جاسم
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkaPH/DwAD+gH/52b1kAAAAABJRU5ErkJggg==", // ياسر ياسين ناجي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/fr/DwAE9gHT4s1n0wAAAABJRU5ErkJggg==", // ياسين رياض احمد
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6YgAAAABJRU5ErkJggg==", // زهراء طه تقي
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWDP5DwAC8AFLpe3eIwAAAABJRU5ErkJggg==", // يحيى فارس محمد
];
